# Example: How to use the security scanner from a consumer repository

name: 'Example Security Scan Usage'

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  security-scan:
    uses: witmicko/security-scanner-monorepo/.github/workflows/security-scan.yml@main
    with:
      repo: ${{ github.repository }}
      languages: '["javascript", "typescript", "python"]' # Adjust based on your repo
      paths_ignored: |
        .storybook/
        '**/__snapshots__/'
        '**/*.snap'
        '**/*.stories.js'
        '**/*.test.js*'
        '**/*.test.ts*'
        '**/fixtures/'
        '**/mocks/  '
        '**/test*/'
        docs/
        node_modules
      rules_excluded: |
        rule1
        rule2
      project_metrics_token: ${{ secrets.SECURITY_SCAN_METRICS_TOKEN }}
      slack_webhook: ${{ secrets.APPSEC_BOT_SLACK_WEBHOOK }}
    permissions:
      actions: read
      contents: read
      security-events: write
