name: 'Local Test - Security Scan'

on:
  workflow_dispatch:
  push:
    branches: [test-*]

jobs:
  # Test our main CI pipeline first
  monorepo-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run package validation
        run: yarn check

      - name: Run action validation
        run: yarn validate

      - name: Run linting
        run: yarn lint

  # Test security scan workflow (simplified for local testing)
  security-scan-test:
    uses: ./.github/workflows/security-scan.yml
    with:
      repo: ${{ github.repository }}
      languages: '["javascript"]'  # Simplified for local testing
      paths_ignored: 'node_modules/,dist/,test/'
    permissions:
      actions: read
      contents: read
      security-events: write